[build]
builder = "nixpacks"
buildCommand = "python3 -m pip install -r ml_services/requirements.txt"

[deploy]
startCommand = "python3 -m uvicorn app:app --host 0.0.0.0 --port $PORT --app-dir ml_services"